# SSH keypair, auto-generated by CloudStack (no public_key supplied).

resource "cloudstack_ssh_keypair" "kp" {
  name = "tf-rc-test-keypair"
}

output "keypair_fingerprint" {
  value = cloudstack_ssh_keypair.kp.fingerprint
}
